### ISSUE TITLE
Raster integration

### ISSUE THREAD

**Issue by TimotheeMichon** [mapmint/mapmint#5]
Hello,

I have some troubles with the integration of raster data.

The recompilation of my raster tools did not really help. Note that, this recompilation produced the following error for one WPS:

```
g++ -I/usr/local/include -I../../../thirds/cgic206/ -I../../zoo-kernel/ -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -I/usr/include -frounding-math -fPIC -DLINUX_FREE_ISSUE  -c ./cgal_service.c
In file included from ./cgal_service.c:24:0:
./cgal_service.h:28:64: fatal error: CGAL/Exact_predicates_inexact_constructions_kernel.h: Aucun fichier ou dossier de ce type
 #include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

```

The classification of raster data seems to work properly, so i think this is not the source of my original problem... Indeed, after the classification process which is a success, i can't display the raster map.
When i try to save the properties of the raster data i have got the following error : 

`
TRACE: msProcessProjection(): Projection library error. proj error "projection not named" for "" <class '_mapscript.MapServerError'> Unable to run your python process properly. Please check the following messages : [' File "/home/src/mapmint/mapmint-services/mapfile/service.py", line 3607, in setMapLayerProperties\n m0=mapscript.mapObj(conf["main"]["dataPath"]+"/maps/search_"+mf+"_"+lname+".map")\n', ' File "/usr/lib/python2.7/dist-packages/mapscript.py", line 1005, in __init__\n _mapscript.mapObj_swiginit(self,_mapscript.new_mapObj(filename))\n']

`

This makes me think that the issue come from the projection of the raster map...?

Thanks for helping me !

Timothée

**Comment by gfenoy** [comment]
Many thanks for your report Timothée.

The issue you had was probably about building the CGAL services. They are not used in MapMint, so you should not try to build it. In case you want to build those services you will require to setup the CGAL library.

I guess that the issue is not due to the rater-tools anymore, is should come from your data that does not seem to have any SRS defined.

Unfortunately, from what I can see we do not provide in the Distiller any tools that offer the same capabilities to reproject the data as provided for the vector layers.

So the best way is probably to reproject your data directly from the command line, by using the `gdalwarp` tool (see here for more details about the command http://www.gdal.org/gdalwarp.html).

Note that this gdalwarp command line is available as a WPS service named `Gdal_Warp` but as there is no HTML form to interact with it, there is no direct way to use it except by writing the `raster-tools.Gdal_Warp` Execute request. Note that it works in the same manner than the command line tool, so it takes the same parameters.

In case you need any sample request to invoke the reproject directly online, you may use something like the following:

`http://myserver.net/cgi-bin/mm/zoo_loader.cgi?service=WPS&version=1.0.0&request=Execute&Identifier=raster-tools.Gdal_Warp&DataInputs=InputDSN=dirs/MYDIR/myraster.format;OutputDSN=myfile;of=GeoTiff;s_srs=IGNF:LAMB93;t_srs=EPSG:4326;a=true&RawDataOutput=Result`

In case it succeeds it should produce a file named `myfile.tif` in the `tmpPath` defined in your `main.cfg` file located in `/usr/lib/cgi-bin/mm/`. This file can then be copied in an existing subdirectory of `/var/data/dirs/` to become accessible to your Distiller, obviously, you will have to make sure to have refreshed your data store first.

I hope you can let us know if your issue was solved this way.

**Comment by TimotheeMichon** [comment]
Hello Gerald,

As you proposed, i tried to reproject my raster type data using the gdalwrap command line tool.
I used the following command : 
`gdalwarp -s_srs IGNF:LAMB93 myASCRasterFile.asc myTIFRasterFile.tif`
The result was the raster `myNewTIFRaster.tif` which i could import by using the Distiller.
After the integration of the data which was a success, both the classification and the display also worked properly in the Manager.

So, the original problem was about the SRS definition of my ASC raster data type. In my case, the reproduction by using gdalwarp seem to be a good solution.

Thanks a lot for all your advices !
